import { FileCheck2, FileSignature, ShieldCheck } from 'lucide-react'
import { usePortalRows } from '../../hooks/usePortalRows'
import { ComingSoonBanner, PortalEmpty, PortalError, PortalLoading } from '../../components/portal/AsyncState'

export default function DocumentsPage() {
  const templates = usePortalRows('document_templates', { orderBy: 'display_order', ascending: true, limit: 100 })
  if (templates.loading) return <PortalLoading label="Loading controlled document metadata" />
  if (templates.error) return <PortalError message={templates.error} retry={() => void templates.reload()} />
  return <section className="portal-library-view" aria-labelledby="documents-heading"><div className="workspace-view-heading"><div><span>DOCUMENTS / METADATA ONLY</span><h2 id="documents-heading">Transaction template register</h2><p>Legal documents remain inactive placeholders until CMAC supplies approved content and contract signing is enabled.</p></div><span className="workspace-live-chip"><FileCheck2 size={14} /> {templates.rows.length} records</span></div><ComingSoonBanner title="DocuSign templates and signing are coming soon" copy="Template metadata can be reviewed now, but no envelope will be created or presented as sent during this release." /><div className="configuration-state"><ShieldCheck size={17} /><div><strong>No repository media is assumed approved</strong><span>Customer marketing and legal transaction documents are separately controlled in private Storage.</span></div></div>{templates.rows.length === 0 ? <PortalEmpty title="No document metadata" copy="An administrator can add controlled template records after legal approval." /> : <div className="template-register">{templates.rows.map((template) => <article key={String(template.id)}><span className="template-file-icon"><FileSignature size={20} /></span><div><small>{String(template.category).toUpperCase()} / {String(template.slug)}</small><h3>{String(template.title)}</h3><p>{String(template.description ?? '')}</p></div><span className={`status-pill ${template.is_active ? 'status-completed' : 'status-draft'}`}>{template.is_active ? 'Provider ready' : 'Placeholder'}</span><dl><div><dt>Provider</dt><dd>{String(template.provider ?? 'Not mapped')}</dd></div><div><dt>Template ID</dt><dd>{template.provider_template_id ? 'Configured' : 'Not configured'}</dd></div></dl></article>)}</div>}</section>
}
